theme: jekyll-theme-minimal
title: Models of Pluralistic Ignorance
description: 'The models below were prepared to support the paper "Emergence of Pluralistic Ignorance: An Agent-Based Approach" (K. Sznajd-Weron & B. Kamińska, 2025). They allow not only to run simulations but also to follow the algorithms step by step.''